remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Hello-World]
description: [A sample github pages website]

show_downloads: ["true"]
#google_analytics: [Your Google Analytics tracking ID]
